### PR TITLE
Jack base animations (batch 1)

### PR DESCRIPTION
**Pull request by RechieKho**
#4 Completed. Please review.

### CODE REVIEW

**Review by dennwc — APPROVED** [review]
Looks good to me. Waiting for ACK from @paperjack93 as well.

**Comment by paperjack93** [comment]
Animations are all there

**Review by paperjack93 — APPROVED** [review]

**Comment by paperjack93** [comment]
@RechieKho please make sure to include the images in the .blend file next time, please

**Comment by dennwc** [comment]
@paperjack93 that's impossible, we cannot include any references since they are under copyright. Instead, the plan is to provide the tooling to extract these assets for the installation you own.

**Pull request merged**
